[package]
name = "wasm-of-life"
version = "0.1.0"
authors = ["Ivan Vologdin <vologdin.nsk@gmail.com>"]

[dependencies]
lazy_static = "1.0"
rand = "0.4.1"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
